services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    networks:
      - unraid
    ports:
      - 22:22
      - 3000:3000
    volumes:
      - /mnt/user/appdata/cache/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
networks:
  unraid:
    external: true
