<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'oci1i6809sbh',
  'passwordsalt' => 'changme',
  'secret' => 'changme',
  'trusted_domains' => 
  array (
    0 => '10.1.50.84:444',
    1 => 'nextcloud.domain.org',
    2 => 'www.nextcloud.domain.org',
    3 => 'https://nextcloud.domain.org',
  ),
  'trusted_proxies' => 
  array (
    0 => '10.1.50.64',
  ),
  'dbtype' => 'mysql',
  'version' => '31.0.7.1',
  'overwrite.cli.url' => 'https://10.1.50:444',
  'dbname' => 'nextcloud',
  'dbhost' => '10.1.50.84:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'changme',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'maintenance' => false,
  'default_phone_region' => 'ISO 3166-2:US',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\Image',
    2 => 'OC\\Preview\\Movie',
    3 => 'OC\\Preview\\MP4',
    4 => 'OC\\Preview\\MOV',
    5 => 'OC\\Preview\\HEVC',
    6 => 'OC\\Preview\\HEIC',
    7 => 'OC\\Preview\\JPEG',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '10.1.50.84',
    'port' => 6378,
    'password' => 'changme',
  ),
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'email',
  'mail_domain' => 'tld',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.domain.tld',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'email@domain.tld',
  'mail_smtppassword' => 'changme',
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpsecure' => 'ssl',
  'memories.exiftool' => '/config/www/nextcloud/apps/memories/bin-ext/exiftool-amd64-musl',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'memories.vod.path' => '/config/www/nextcloud/apps/memories/bin-ext/go-vod-amd64',
  'memories.vod.disable' => false,
  'filelocking.enabled' => 'true',
  'app_install_overwrite' => 
  array (
    0 => 'memories',
  ),
  'upgrade.disable-web' => true,
  'memories.db.triggers.fcu' => true,
);
